version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    networks:
      - app-network
    ports:
      - 5672:5672
      - 15672:15672
  stock-service:
    image: deliverymuch/backend-challenge:stock-service
    networks:
      - app-network
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    restart: on-failure
  db:
    image: mdillon/postgis:10
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_DB: database
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    ports:
      - 15432:5432
networks:
  app-network:
    driver: bridge
